name: Winfirm Trade Club
url: https://panxw.github.io
description: None

permalink: /:categories/:title.html
category_names: ['Home','Android','Program','Linux','Git','Web','Others','About']
#gems: [jekyll-paginate]
highlighter: pygments
paginate: 20

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins: ['jekyll-paginate']
